server:
  port: 80


feign:
  hystrix:
    enabled: true

#以前我们直接就访问微服务了，现在由于有了eureka，所以我们需要先找eureka
eureka:
  client:
    #我们是consumer，所以不需要把自己注册进eureka
    register-with-eureka: false
    #到哪几个eureka里找服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
