server:
  port: 8002

mybatis:
  #一般不用配这个配置文件
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件


spring:
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02              # 数据库名称
    username: root
    password: 88888888




eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#显示在Eureka主页的本服务实例的Status栏的地址，不写这行的话，默认是IP+端口号+/info
  instance:
    instance-id: microservicecloud-dept8002
#Eureka主页的实例访问路径可以显示IP地址（就是你鼠标放在Status列上的时候，浏览器左下角显示的地址），不加的话显示的是localhost/nightWalker之类的主机名
    prefer-ip-address: true

#追加微服务的信息描述，这里的info就是eureka主页中各服务实例的跳转连接（鼠标放上去，左下角）的/info页面中显示的内容
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$













